const consts = {
  USER_UPDATE: "USER_UPDATE",
  LOGIN: "AUTH_LOGIN",
  LOGOUT: "AUTH_LOGOUT",
  LOADED: "LODADED",
  RESIZE: "RESIZE",
  SNACKS: {
    ENQUEUE_SNACK: "ENQUEUE_SNACK",
    CLOSE_SNACK: "CLOSE_SNACK",
    REMOVE_SNACK: "REMOVE_SNACK",
  },
  PEOPLE: {
    PEOPLE_LOAD: "PEOPLE_LOAD",
    PEOPLE_ADD: "PEOPLE_ADD",
    PEOPLE_REMOVE: "PEOPLE_REMOVE",
  },
  APP: {
    READY: "APP_READY",
  },
  GAME: {
    LOAD: "LOAD_GAME",
    CREATE: "CREATE_GAME",
    ADD_PLAYER: "ADD_PLAYER",
    UPDATE_STATUS: "UPDATE_STATUS"
  },
  PLAYERS: {
    LOAD_ONE: "PLAYER_LOAD",
    LOAD_FROM_GAME: "PLAYERS_LOAD_FROM_GAME"
  },
  ZONE: {
    LOAD: "LOAD_ZONES",
    LOAD_ONE: "LOAD_A_ZONE"
  },
  MODALS: {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
  },
};

export default consts;
