const consts = {
  USER_UPDATE: "USER_UPDATE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  LOADED: "LODADED",
  RESIZE: "RESIZE",
  SNACKS: {
    ENQUEUE_SNACK: "ENQUEUE_SNACK",
    CLOSE_SNACK: "CLOSE_SNACK",
    REMOVE_SNACK: "REMOVE_SNACK",
  },
  PEOPLE: {
    PEOPLE_LOAD: "PEOPLE_LOAD",
    PEOPLE_ADD: "PEOPLE_ADD",
    PEOPLE_REMOVE: "PEOPLE_REMOVE",
  },
  LOAD_ZONES: "LOAD_ZONES",
  MODALS: {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
  },
};

export default consts;
